Prediction of the price of the cars

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importing file 
df = pd.read_csv('car_price_prediction.csv')
df.head()

,Car_ID,Brand,Model,Body_Type,Year,Car_Age_Years,Fuel_Type,Transmission,Owner_Type,Kms_Driven,Engine_CC,Power_BHP,Mileage_kmpl,Seats,Selling_Price_Lakh_INR
0,L0001,Audi,Q7,SUV,2024,2,Diesel,Automatic,First,17000,2967,250.5,15.1,7,76.31
1,L0002,Land Rover,Discovery Sport,SUV,2021,5,Diesel,Automatic,First,53400,1999,176.4,16.2,7,37.31
2,L0003,Ferrari,Portofino,Coupe,2024,2,Petrol,Automatic,First,2400,3855,581.9,8.5,4,290.25
3,L0004,BMW,3 Series,Sedan,2022,4,Petrol,Automatic,Second,42100,1998,255.2,9.8,5,31.41
4,L0005,BMW,X5,SUV,2023,3,Petrol,Automatic,First,22800,2998,325.0,10.8,5,71.82

In [3]:
df.describe()

,Year,Car_Age_Years,Kms_Driven,Engine_CC,Power_BHP,Mileage_kmpl,Seats,Selling_Price_Lakh_INR
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2021.198000,4.802000,46414.800000,2377.786000,252.962800,13.154200,5.054000,62.289460
std,3.075339,3.075339,29839.309472,773.961716,94.769264,3.164223,0.582892,54.371018
min,2012.000000,1.000000,2400.000000,1496.000000,132.700000,5.500000,4.000000,7.500000
25%,2019.000000,2.000000,22800.000000,1968.750000,190.700000,10.600000,5.000000,32.470000
50%,2022.000000,4.000000,40400.000000,1997.000000,217.350000,12.850000,5.000000,45.440000
75%,2024.000000,7.000000,65900.000000,2967.000000,271.950000,15.900000,5.000000,65.470000
max,2025.000000,14.000000,147200.000000,6592.000000,638.900000,19.800000,7.000000,536.210000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Car_ID                  500 non-null    str
 1   Brand                   500 non-null    str
 2   Model                   500 non-null    str
 3   Body_Type               500 non-null    str
 4   Year                    500 non-null    int64
 5   Car_Age_Years           500 non-null    int64
 6   Fuel_Type               500 non-null    str
 7   Transmission            500 non-null    str
 8   Owner_Type              500 non-null    str
 9   Kms_Driven              500 non-null    int64
 10  Engine_CC               500 non-null    int64
 11  Power_BHP               500 non-null    float64
 12  Mileage_kmpl            500 non-null    float64
 13  Seats                   500 non-null    int64
 14  Selling_Price_Lakh_INR  500 non-null    float64
dtypes: float64(3), int64(5), str(7)
memory usage: 79.5 KB

In [5]:
df.isnull().sum()

Car_ID                    0
Brand                     0
Model                     0
Body_Type                 0
Year                      0
Car_Age_Years             0
Fuel_Type                 0
Transmission              0
Owner_Type                0
Kms_Driven                0
Engine_CC                 0
Power_BHP                 0
Mileage_kmpl              0
Seats                     0
Selling_Price_Lakh_INR    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.head()

,Car_ID,Brand,Model,Body_Type,Year,Car_Age_Years,Fuel_Type,Transmission,Owner_Type,Kms_Driven,Engine_CC,Power_BHP,Mileage_kmpl,Seats,Selling_Price_Lakh_INR
0,L0001,Audi,Q7,SUV,2024,2,Diesel,Automatic,First,17000,2967,250.5,15.1,7,76.31
1,L0002,Land Rover,Discovery Sport,SUV,2021,5,Diesel,Automatic,First,53400,1999,176.4,16.2,7,37.31
2,L0003,Ferrari,Portofino,Coupe,2024,2,Petrol,Automatic,First,2400,3855,581.9,8.5,4,290.25
3,L0004,BMW,3 Series,Sedan,2022,4,Petrol,Automatic,Second,42100,1998,255.2,9.8,5,31.41
4,L0005,BMW,X5,SUV,2023,3,Petrol,Automatic,First,22800,2998,325.0,10.8,5,71.82

In [8]:
# Renaming the column

df.rename(columns={'Selling_Price_Lakh_INR' : 'Price'}, inplace = True)
df.head()

,Car_ID,Brand,Model,Body_Type,Year,Car_Age_Years,Fuel_Type,Transmission,Owner_Type,Kms_Driven,Engine_CC,Power_BHP,Mileage_kmpl,Seats,Price
0,L0001,Audi,Q7,SUV,2024,2,Diesel,Automatic,First,17000,2967,250.5,15.1,7,76.31
1,L0002,Land Rover,Discovery Sport,SUV,2021,5,Diesel,Automatic,First,53400,1999,176.4,16.2,7,37.31
2,L0003,Ferrari,Portofino,Coupe,2024,2,Petrol,Automatic,First,2400,3855,581.9,8.5,4,290.25
3,L0004,BMW,3 Series,Sedan,2022,4,Petrol,Automatic,Second,42100,1998,255.2,9.8,5,31.41
4,L0005,BMW,X5,SUV,2023,3,Petrol,Automatic,First,22800,2998,325.0,10.8,5,71.82

In [9]:
#   Encoding of Catogrical columns 

df = pd.get_dummies(df,columns=['Brand','Model','Body_Type','Fuel_Type',
        'Transmission','Owner_Type'],drop_first=True, dtype=int)
df

,Car_ID,Year,Car_Age_Years,Kms_Driven,Engine_CC,Power_BHP,Mileage_kmpl,Seats,Price,Brand_BMW,...,Model_XC90,Model_XF,Body_Type_Hatchback,Body_Type_SUV,Body_Type_Sedan,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Manual,Owner_Type_Second,Owner_Type_Third
0,L0001,2024,2,17000,2967,250.5,15.1,7,76.31,0,...,0,0,0,1,0,0,0,0,0,0
1,L0002,2021,5,53400,1999,176.4,16.2,7,37.31,0,...,0,0,0,1,0,0,0,0,0,0
2,L0003,2024,2,2400,3855,581.9,8.5,4,290.25,0,...,0,0,0,0,0,0,1,0,0,0
3,L0004,2022,4,42100,1998,255.2,9.8,5,31.41,1,...,0,0,0,0,1,0,1,0,1,0
4,L0005,2023,3,22800,2998,325.0,10.8,5,71.82,1,...,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,L0496,2022,4,53400,1997,246.2,11.1,5,33.10,0,...,0,0,0,1,0,0,1,0,1,0
496,L0497,2021,5,35300,3996,506.7,7.3,4,112.53,0,...,0,0,0,0,0,0,1,0,0,0
497,L0498,2024,2,19500,1995,190.0,16.8,5,49.46,1,...,0,0,0,0,1,0,0,0,0,0
498,L0499,2022,4,37100,1995,148.4,16.7,5,34.10,1,...,0,0,0,1,0,0,0,0,0,0
499,L0500,2025,1,23000,1984,187.0,11.0,5,42.18,0,...,0,0,0,1,0,0,1,0,0,0

In [10]:
#  Droping of unwanted Column 

df = df.drop('Car_ID', axis=1)
df

,Year,Car_Age_Years,Kms_Driven,Engine_CC,Power_BHP,Mileage_kmpl,Seats,Price,Brand_BMW,Brand_Bentley,...,Model_XC90,Model_XF,Body_Type_Hatchback,Body_Type_SUV,Body_Type_Sedan,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Manual,Owner_Type_Second,Owner_Type_Third
0,2024,2,17000,2967,250.5,15.1,7,76.31,0,0,...,0,0,0,1,0,0,0,0,0,0
1,2021,5,53400,1999,176.4,16.2,7,37.31,0,0,...,0,0,0,1,0,0,0,0,0,0
2,2024,2,2400,3855,581.9,8.5,4,290.25,0,0,...,0,0,0,0,0,0,1,0,0,0
3,2022,4,42100,1998,255.2,9.8,5,31.41,1,0,...,0,0,0,0,1,0,1,0,1,0
4,2023,3,22800,2998,325.0,10.8,5,71.82,1,0,...,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2022,4,53400,1997,246.2,11.1,5,33.10,0,0,...,0,0,0,1,0,0,1,0,1,0
496,2021,5,35300,3996,506.7,7.3,4,112.53,0,0,...,0,0,0,0,0,0,1,0,0,0
497,2024,2,19500,1995,190.0,16.8,5,49.46,1,0,...,0,0,0,0,1,0,0,0,0,0
498,2022,4,37100,1995,148.4,16.7,5,34.10,1,0,...,0,0,0,1,0,0,0,0,0,0
499,2025,1,23000,1984,187.0,11.0,5,42.18,0,0,...,0,0,0,1,0,0,1,0,0,0

In [11]:
# Importing input and output columns in variable.

X = df.drop('Price', axis=1)
y = df['Price']

In [12]:
#  Training & Teasting of columns.

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [13]:
#  applying polynomial feature in columns which do not have consistancy in data.

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

poly_cols = ["Kms_Driven", "Engine_CC", "Power_BHP", "Car_Age_Years"]

# creating object of the model
poly = PolynomialFeatures(degree=2)


#  fitting the data in model

poly_train = pd.DataFrame(poly.fit_transform(X_train[poly_cols]),columns= poly.get_feature_names_out(poly_cols), index=X_train.index)
poly_test = pd.DataFrame(poly.transform(X_test[poly_cols]), columns=poly.get_feature_names_out(poly_cols), index= X_test.index)


# droping of old data and concatination of new data gotted by fitting

X_train2= pd.concat([X_train.drop(columns=poly_cols), poly_train], axis=1)
X_test2 = pd.concat([X_test.drop(columns=poly_cols),poly_test],axis=1)


# scaling of data to make the low difference between data.

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train2)
X_test_scaled = scaler.fit_transform(X_test2)


# importing linear regression for prediction
from sklearn.linear_model import LinearRegression

# creating object of the model
model = LinearRegression()

#  fitting the data in model
model.fit(X_train_scaled,y_train)

# prediction of the model
predict = model.predict(X_test_scaled)


# checking the accuracy of working model 
from sklearn.metrics import r2_score

r2 = r2_score(predict,y_test)
r2

0.8287599158673773

In [14]:
# Creating a streamlit file

import joblib
joblib.dump(model,'car_price_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X.columns.to_list(), 'columns.pkl')

['columns.pkl']